[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

[phases.start]
dependsOn = ["build"]
cmds = ["npm run start"]
