[[phases]]
name = "setup"
nixPkgs = ["nodejs_18", "pnpm"]

[[phases]]
name = "install"
cmds = ["pnpm install"]

[[phases]]
name = "build"
cmds = ["pnpm run build"]

[[phases]]
name = "start"
cmds = ["pnpm run start"]
